import { z } from 'zod';

export const AgentActionSchema = z.enum(['purchase', 'refund', 'payout', 'query']);
export type AgentAction = z.infer<typeof AgentActionSchema>;

export const CurrencyCodeSchema = z.enum(['INR', 'USD', 'EUR', 'GBP']);
export type CurrencyCode = z.infer<typeof CurrencyCodeSchema>;

export const PaymentIntentStateSchema = z.enum([
  'PENDING',
  'POLICY_CHECK',
  'RISK_CHECK',
  'REVIEW_REQUIRED',
  'AUTHORIZED',
  'EXECUTING',
  'SUCCEEDED',
  'FAILED',
  'BLOCKED',
]);
export type PaymentIntentState = z.infer<typeof PaymentIntentStateSchema>;

/**
 * Natural language intent input submitted by user or client agent.
 */
export const AgentIntentRequestSchema = z.object({
  prompt: z.string().min(1, 'Prompt cannot be empty').max(2000, 'Prompt too long'),
  agentId: z.string().min(1, 'agentId is required'),
  userId: z.string().min(1, 'userId is required'),
  authorizationToken: z.string().optional(),
  idempotencyKey: z.string().optional(),
  metadata: z.record(z.unknown()).optional().default({}),
});
export type AgentIntentRequest = z.input<typeof AgentIntentRequestSchema>;
export type AgentIntentRequestValidated = z.output<typeof AgentIntentRequestSchema>;

/**
 * Structured payment intent generated by LLM parser.
 * Strict numeric bounds: amountPaise MUST be a positive integer minor unit (1 INR = 100 paise).
 */
export const StructuredAgentIntentSchema = z.object({
  action: AgentActionSchema,
  category: z.string().min(1).max(100),
  amountPaise: z.number().int('Amount must be an integer in minor units (paise)').positive('Amount must be greater than 0'),
  currency: CurrencyCodeSchema.default('INR'),
  merchantName: z.string().min(1).max(100),
  merchantCategory: z.string().optional(),
  intentDetails: z.string().max(500).optional(),
  rawPrompt: z.string().optional(),
  confidence: z.number().min(0).max(1).optional(),
});
export type StructuredAgentIntent = z.infer<typeof StructuredAgentIntentSchema>;

/**
 * Payment intent domain model representation DTO.
 */
export const PaymentIntentDTOSchema = z.object({
  id: z.string().uuid(),
  userId: z.string(),
  agentId: z.string(),
  state: PaymentIntentStateSchema,
  amountPaise: z.number().int().positive(),
  currency: CurrencyCodeSchema,
  merchantName: z.string(),
  merchantCategory: z.string().nullable().optional(),
  rawPrompt: z.string(),
  idempotencyKey: z.string(),
  authorizationToken: z.string().nullable().optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type PaymentIntentDTO = z.infer<typeof PaymentIntentDTOSchema>;
